### ISSUE TITLE
Idea: Add subtemplating feature

### ISSUE THREAD

**Issue by kydorn** [markround/tiller#19]
It would be nice the ability to define subtemplates that can be reused inside regular erb templates.

I was thinking about something like <%= import('whateverfile.erb') %>, which would have the same binding as the parent template.

What do you think?

**Comment by markround** [comment]
Another great idea! Just tidying up after 0.7.8 release/Consul plugin, but I'll get on this as the next feature.

**Comment by kydorn** [comment]
Nice :) Thanks a lot for everything!

**Comment by markround** [comment]
On it now. Going to make it a part of a "custom tags" feature where you can add your own functions to templates, and bundle it as a 'render' function. So you'll be able to do stuff like

```erb
<%= Tiller::render('sub_template.erb') %> 
```

in your templates.

**Comment by kydorn** [comment]
That looks very nice :) About the custom tags feature, will we be able to define them outside Tiller code?

**Comment by markround** [comment]
Yeah, that's the idea. Take a look at https://github.com/markround/tiller/blob/a165f3af76cc414fcc83a8712bf47a5c238fc881/features/helpers.feature for a test-case, and that commit as a whole to see the implementation.

I decided on calling them 'helper modules' instead of 'tags', because that better describes them - and you can write one module with a bunch of useful functions in.

**Comment by markround** [comment]
Released as part of 0.8.0. Thanks again for the idea!
