### ISSUE TITLE
Idea: Support environment-based yaml overrides

### ISSUE THREAD

**Issue by kydorn** [markround/tiller#20]
Esentially like environment_json, but with yaml. Seems more consistent to use yaml all the way, and not yaml in some places and json if you need to override

**Comment by markround** [comment]
Good idea. Might be a bit tricky, as YAML is very whitespace sensitive, but I'll take a look.

**Comment by kydorn** [comment]
I'm currently using yaml, and converting it to json. If you use quotes for strings it actually works fine.

**Comment by markround** [comment]
Hi,

Had a thought about this. YAML as an environment variable is sort of nasty, in that you have to worry about newlines, escaping and so on. Also, complicated JSON structures usually got passed in by 'cat'ing the file, like `tiller_json=$(cat json_file.json) .....` anyway.

How about instead of another environment plugin, I make a generic 'external_file' plugin ? You could then do something like this in `common.yaml`:

```
external_files:
  - /configs/application_config.json
  - /configs/credentials.yml
```

Then, the plugin would auto-parse the files and make the data structures inside them available. When using Tiller inside a Docker container, you could then simply map the files in, e.g.

`docker run -v ./configs:/configs .........` and so on. What do you think ? This could be a very useful method of allowing an end-user to provide their own values for a container, and would also solve your "pass arbitary YAML" issue in a slightly different way ?

**Comment by markround** [comment]
Initial draft implementation at https://github.com/markround/tiller/commit/8b61308807d59ffe8beb490e9470ec7c0cf20ea7. You can see the plugin, along with the test & fixtures (config file, template and external files).

**Comment by kydorn** [comment]
hmm this would work for me, but if you could use environment variables in the yaml it would be amazing (like docker compose). If not, it would be quite static, and other than just convenience, equivalent to a single file already merged

**Comment by markround** [comment]
Closing this issue as the change was merged and released. I'll take another look at the YAML env vars stuff, YAML itself doesn't support it but there might be a way of looking up other variables or doing some sort of interpolation inside the YAML file. But it'll need careful design so it doesn't break anything or interpret string literals as vars etc.
