### ISSUE TITLE
Use SHA/MD5 hash before writing a template-file to avoid EXEC calls when not needed

### ISSUE THREAD

**Issue by EugenMayer** [markround/tiller#30]
One of the biggest issues with tiller is, when combined with 'consul watch' or at least with iterated runs, that you restart a service ( EXEC command ) without any reason, when nothing changed.

Since a lot of those services could be heavy duty ( DB ) and have a longer bootstrap time (and no config reload command ) or at least have something like opcache-flush ( php-fpm ) when reloaded / restarted, this becomes a very costy implementation in production systems:

My proposal:
Its fairly simple:
 - when the ERB template has been rendered, calculate a md5 hash ( fast, no need to have it secure ) of the generated one, generate a md5 hash of the target, if they match, write something in the logs and cleanly bail out without writing and without running exec.
 - if either the MD5 sums do not match or the target does yet not exist, normal behavior ( write and exec )

What do you think?

UPDATE:
also add an option to disable the checksum-checking or lets call it "exec-on-changes-only" - i my world of tiller, this should be defaulting to true, since it makes sense for all of us - if there happen to be an exception, it should be an opt out.

**Comment by EugenMayer** [comment]
any news on this one? really looking forward to this

**Comment by markround** [comment]
On it now :)

**Comment by markround** [comment]
Hi,

Just pushed a first implementation at https://github.com/markround/tiller/tree/feature/md5.

Because this changes the way Tiller writes templates, I decided to make this an "opt-in" feature for now, as this may conceivably affect other people's setups. We can always make it opt-out in a future major point release (e.g. 0.8.x). 

The README.md in that branch has been updated with details on how to enable these features, you can either pass in `--md5sum` and `--md5sum-noexec` on the command line, or set the following in your `common.yaml`:

```yaml
md5sum: true
md5sum_noexec: true
```

With those both set, Tiller will only execute a process if at least one template has been written:

```
...
[0/2] templates written, [2] skipped with no change
Template generation completed
No templates written, stopping without exec
```


You can see the feature tests which illustrate this here: https://github.com/markround/tiller/blob/feature/md5/features/md5sum_files.feature and https://github.com/markround/tiller/blob/feature/md5/features/md5sum_noexec.feature.

**Comment by EugenMayer** [comment]
Wow, great news! I am for myself totally fine with an opt-in - but thinking about what should be the default without legacy in mind, i would ten to say opt-out is the better solution.

I guess, you just want to see how many people use this and then decide, if that is useful.

**Comment by EugenMayer** [comment]
I will test this when i am at home, thank you a lot @markround !

**Comment by markround** [comment]
You're welcome. Please let me know if you're happy with it, and I'll merge it and release a new version.

**Comment by markround** [comment]
Closing as now in 0.7.10. Please open a new issue with any suggestions/improvements for this feature. Thanks again!
