### ISSUE TITLE
Support non-shell syntax for exec command with arguments

### ISSUE THREAD

**Issue by jjongsma** [markround/tiller#8]
The only way to execute a command with arguments is to pass it as a string:

```
exec: /usr/local/bin/app -f argument
```

When passed to `exec()`, that results in execution by the default shell, which has problems when it comes to propagating signals (meaning unnecessary SIGKILLs when docker stops).

If `config['exec']` is an array, you should explode it to use the kernel exec method, which propagates signals correctly:

YAML:
```yaml
exec: ["/usr/local/bin/app", "-f", "argument"]
```

Ruby:
```ruby
exec(*config['exec'])
```

https://github.com/markround/tiller/blob/master/bin/tiller#L165

**Comment by jjongsma** [comment]
I see your latest release attempts to propagate signals to the child to avoid zombies, but I don't think it solves the "graceful shutdown" problem yet, which this method should do.

http://ruby-doc.org//core-2.0.0/Kernel.html#method-i-exec

**Comment by markround** [comment]
Thanks for the feedback! I'll look into this.

**Comment by markround** [comment]
It's a little more complicated than I first thought due to the way arguments are passed to spawn() and friends when using the array-form. However, I think I have a nice solution that I'm working on. It'll require the user to specify an array structure (a bit like Docker's CMD), so they could still use the old (current) syntax, e.g.
```
exec: /usr/bin/foo -v -l /var/log/foo.log
```
Which would spawn the default shell and be subject to shell expansion, or they could explicitly specify:
```
exec: [ "/usr/bin/foo", "-v", "-l", "/var/log/foo.log" ]
```
To get the new behaviour.

**Comment by markround** [comment]
OK, pushed a first version of this into /develop branch.

**Comment by markround** [comment]
Release 0.5.1 should now handle this, so I'm closing this issue. Please re-open if there's any problem with it, and thanks again for the feedback!

**Comment by jjongsma** [comment]
Looks like it should do the trick, I'll try it out.
